# Generated by Django 5.1.7 on 2025-03-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='workshop',
        ),
        migrations.AddField(
            model_name='workshop',
            name='speaker',
            field=models.ManyToManyField(related_name='workshops', to='workshop.speaker'),
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
