# Generated by Django 5.1.7 on 2025-03-17 21:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_speaker_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('multiline', 'Multiline'), ('number', 'Number'), ('file', 'File Upload'), ('checkbox', 'Checkbox'), ('select', 'Dropdown'), ('multi_select', 'Multiple Dropdown'), ('radio', 'Radio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationresponse',
            name='response_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
