# Generated by Django 5.1.7 on 2025-03-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_remove_workshop_organizer_remove_speaker_workshop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
